### ISSUE TITLE
How to deal with Orders not completed by (or even delivered to) an AGV?

### ISSUE THREAD

**Issue by krisl** [coatyio/vda-5050-lib.js#12]
**Describe the bug**
`masterController.assignOrder` requires only that the message is published to an MQTT server to resolve the promise with a header.  This does not mean the message has been delivered to an AGV.
If the AGV then goes off line, never to come back, perhaps it never received the message or does not persist it, how to then manage this Order?

The order cannot be sent with `assignOrder` again, it will just be rejected with the promise being resolved with `undefined`.
Sending a `cancelOrder` action does not alter the `MasterController`'s state of the order locally.

A late joining AGV will also not receive the Order, as its not retained.

**To Reproduce**
Run the example code in the `readme.md`, with the `AgvController` joining after the `Order` is published.

**Expected behavior**
Probably just some guidelines around managing the lifecycle of Orders that don't go exactly to plan.
A mechanism to republish?  Or cancel centrally.

**Comment by ffa500** [comment]
The behavior you observe is by design due to VDA 5050 using MQTT pub-sub communication protocol (with QoS 0). 

The promise that `MasterController.assignOrder` returns can only signal the caller that either the order has been published successfully (to the MQTT broker, NOT to any subscribers, i.e. AGV controllers) or that the order has not been sent (order is invalid or has been discarded).

There is never a guarantee that a successfully published order is ever received by a subscriber. The MQTT broker will simply drop the order assignment message if there is no subscriber registered currently. Order messages are not retained according to VDA 5050 specification. Late joining subscribers or subscribers with a (temporary) broken connection will simply miss them. 

You have to handle such cases on the application level by monitoring the order events with the callback functions
passed to `assignOrder`. If no event is received within a certain timeout period, you could assume the message has not been received by the AGV. If your AGV is publishing regular State messages every 30secs, a timeout period of 40-60secs may be appropriate.  To reassign such a missed order, you must republish it using a new orderId or orderUpdateId.

To deal with late joining AGVs, you could also track the connection state (online/offline) of an AGV using 
the vda-5050-lib methods `MasterController.getTrackedState`, `MasterController.getTrackedStates`, or `MasterController.trackAgvs`. You should NOT assign orders if the latest tracked state of a target AGV is offline. But keep in mind that a tracked connection state you receive in your master controller could be already outdated due to the asynchronous nature of the network communication layer. That's were monitoring order events for timeouts comes into play.

There are no plans to integrate such recovery/republish mechanisms into vda-5050-lib.

**Comment by krisl** [comment]
> To reassign such a missed order, you must republish it using a new orderId or orderUpdateId.

Great, that works, thank you very much! 😄 
Interestingly if I publish a new order with a new `orderId`, and that new order is accepted by a connected `AgvController`,  I can now republish the original "stuck" order, with its original `orderId`.

> Order messages are not retained according to VDA 5050 specification.

I didn't see anywhere in the spec v1.1 or v2.0 that says topics _shouldn't_ be retained. Only that the `connection` and `factsheet` topic _should_ be, or _shall_ be in v2.0

Given that the chance of undelivered orders is not insignificant for the reasons you stated above, I imagine between the MQTT broker and the MasterController, they are well placed to engage in some sort of ensuring of delivery.  But indeed perhaps this is not in line with the spec and we can do it in higher level business logic.

**Comment by ffa500** [comment]
Yes, my statement about retained Order messages is not correct. Retaining Order or InstantAction topics could be an option to deal with such cases on the library level. 

BTW, the library already supports retained messages as part of the `options` in the `MasterControlClient.publish` method (`retainMessage` flag). However, until now, these publish options are not available in the `MasterController.assignOrder` method. Maybe a future version will support this...
